version: '3.4'
services: 
  session-db:
        image: "mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu"
        volumes: 
          - sqldata4:/var/opt/mssql  
        ports:
          - 1469:1433
        environment:
          SA_PASSWORD: "yourStrong(!)Password"
          ACCEPT_EULA: "Y"    
volumes:
  sqldata4:       